from django.db import migrations,models
import django.db.models.deletion
from django.core.validators import MinValueValidator,MaxValueValidator
import django.utils.timezone
class Migration(migrations.Migration):
 initial=True; dependencies=[]
 operations=[
  migrations.CreateModel(name='Category',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120,unique=True)),('slug',models.SlugField(blank=True,unique=True)),('image',models.ImageField(blank=True,null=True,upload_to='categories/')),('active',models.BooleanField(default=True))]),
  migrations.CreateModel(name='NewsletterSubscriber',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('email',models.EmailField(max_length=254,unique=True)),('subscribed_at',models.DateTimeField(auto_now_add=True))]),
  migrations.CreateModel(name='Product',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=220)),('slug',models.SlugField(blank=True,unique=True)),('sku',models.CharField(max_length=80,unique=True)),('description',models.TextField(blank=True)),('price',models.DecimalField(decimal_places=2,max_digits=12)),('old_price',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True)),('image',models.ImageField(blank=True,null=True,upload_to='products/')),('image_url',models.URLField(blank=True)),('stock',models.PositiveIntegerField(default=0)),('low_stock_threshold',models.PositiveIntegerField(default=5)),('active',models.BooleanField(default=True)),('featured',models.BooleanField(default=False)),('rating',models.DecimalField(decimal_places=1,default=4.5,max_digits=3,validators=[MinValueValidator(0),MaxValueValidator(5)])),('reviews_count',models.PositiveIntegerField(default=0)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('category',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='products',to='store.category'))]),
  migrations.CreateModel(name='SiteSettings',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('store_name',models.CharField(default='Reeves Boutique',max_length=160)),('logo',models.ImageField(blank=True,null=True,upload_to='branding/')),('primary_color',models.CharField(default='#d97706',max_length=20)),('currency',models.CharField(default='KES',max_length=10)),('low_stock_default',models.PositiveIntegerField(default=5)),('smtp_enabled',models.BooleanField(default=False)),('smtp_host',models.CharField(default='smtp.gmail.com',max_length=160)),('smtp_port',models.PositiveIntegerField(default=587)),('smtp_username',models.CharField(blank=True,max_length=200)),('smtp_password',models.CharField(blank=True,max_length=300)),('smtp_tls',models.BooleanField(default=True)),('from_email',models.EmailField(blank=True,max_length=254)),('mpesa_enabled',models.BooleanField(default=False)),('mpesa_environment',models.CharField(choices=[('sandbox','Sandbox'),('production','Production')],default='sandbox',max_length=20)),('mpesa_consumer_key',models.CharField(blank=True,max_length=300)),('mpesa_consumer_secret',models.CharField(blank=True,max_length=300)),('mpesa_shortcode',models.CharField(blank=True,max_length=50)),('mpesa_passkey',models.CharField(blank=True,max_length=300)),('mpesa_callback_url',models.URLField(blank=True)),('mpesa_account_reference',models.CharField(default='Reeves Boutique',max_length=100)),('mpesa_transaction_desc',models.CharField(default='Payment for Reeves Boutique order',max_length=200)),('updated_at',models.DateTimeField(auto_now=True))]),
  migrations.CreateModel(name='Order',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('number',models.CharField(max_length=30,unique=True)),('customer_name',models.CharField(max_length=160)),('phone',models.CharField(max_length=30)),('email',models.EmailField(blank=True,max_length=254)),('address',models.TextField(blank=True)),('total',models.DecimalField(decimal_places=2,max_digits=12)),('status',models.CharField(choices=[('pending','Pending'),('paid','Paid'),('processing','Processing'),('shipped','Shipped'),('delivered','Delivered'),('cancelled','Cancelled')],default='pending',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))]),
  migrations.CreateModel(name='MpesaTransaction',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('transaction_id',models.CharField(max_length=80,unique=True)),('phone',models.CharField(max_length=30)),('amount',models.DecimalField(decimal_places=2,max_digits=12)),('status',models.CharField(choices=[('sent','Sent'),('completed','Completed'),('failed','Failed')],default='sent',max_length=20)),('checkout_request_id',models.CharField(blank=True,max_length=120)),('mpesa_receipt',models.CharField(blank=True,max_length=80)),('result_description',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('order',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='store.order'))]),
  migrations.CreateModel(name='OrderItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('product_name',models.CharField(max_length=220)),('price',models.DecimalField(decimal_places=2,max_digits=12)),('quantity',models.PositiveIntegerField(default=1)),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='store.order')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='store.product'))]),
 ]
