# Generated by Django 5.2.17 on 2026-08-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_full_ecommerce'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mpesatransaction',
            new_name='store_mpesa_checkou_516bdc_idx',
            old_name='store_mpesa_checkout_4f8a92_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='store_order_status_428b25_idx',
            old_name='store_order_status_6a7f3b_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='store_order_payment_83b142_idx',
            old_name='store_order_payment_1c9d2e_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='store_order_number_3c003b_idx',
            old_name='store_order_number_b8f6a1_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_active_d7c842_idx',
            old_name='store_prod_active_49c3d6_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_stock_3f6dbc_idx',
            old_name='store_prod_stock_5b3f22_idx',
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mpesa_callback_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mpesa_passkey',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
