# Generated by Django 5.2.17 on 2026-08-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_store_mpesa_checkout_4f8a92_idx_store_mpesa_checkou_516bdc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'hidden', 'is_archived'], name='store_produ_active_efcf0e_idx'),
        ),
    ]
