# Generated by Django 5.2.17 on 2026-08-11 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_hidden_product_is_archived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='inventory_alert_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='restock_lead_time_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='restock_lookback_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='restock_min_sales_orders',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low', 'Low stock'), ('out', 'Out of stock')], default='low', max_length=10)),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('stock_at_alert', models.PositiveIntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='store.product')),
            ],
            options={
                'verbose_name': 'Inventory alert',
                'verbose_name_plural': 'Inventory alerts',
                'ordering': ['is_resolved', '-created_at'],
                'indexes': [models.Index(fields=['is_resolved', 'alert_type'], name='store_inven_is_reso_91ca51_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('sale', 'Sold'), ('restock', 'Restocked'), ('adjust', 'Adjusted'), ('release', 'Stock released'), ('threshold', 'Threshold changed'), ('desired', 'Desired level changed')], default='adjust', max_length=20)),
                ('old_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('new_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('change', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_changes', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='store_inven_product_e660b3_idx')],
            },
        ),
    ]
