# Generated by Django 5.2.17 on 2026-08-11 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_success_to_paid(apps, schema_editor):
    """The legacy 'success' payment status is now 'paid'."""
    Order = apps.get_model('store', 'Order')
    Payment = apps.get_model('store', 'Payment')
    Order.objects.filter(payment_status='success').update(payment_status='paid')
    Payment.objects.filter(status='success').update(status='paid')


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sitesettings_inventory_alert_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='action_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='result_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='result_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification',
            field=models.CharField(blank=True, choices=[('', 'Not verified'), ('gateway', 'Gateway verified'), ('manual', 'Manually reviewed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='inventory_strategy',
            field=models.CharField(choices=[('hold', 'Reserve stock when the order is placed'), ('paid', 'Deduct stock when payment is confirmed')], default='hold', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('requires_review', 'Requires Review')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa STK Push'), ('manual', 'Cash / manual')], default='mpesa', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('requires_review', 'Requires Review')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'method'], name='store_payme_status_72d2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='store_payme_order_i_56dfe1_idx'),
        ),
        migrations.RunPython(
            code=migrate_success_to_paid,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
