# Generated by Django 5.2.17 on 2026-08-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_payment_options_order_stock_deducted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='password_reset_timeout_seconds',
            field=models.PositiveIntegerField(default=86400, help_text='How long a password-reset link stays valid, in seconds.'),
        ),
    ]
