# Generated by Django 5.2.17 on 2026-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_sitesettings_password_reset_timeout_seconds'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', 'hidden', 'is_archived', '-created_at'], name='store_produ_active_ee2f66_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='store_produ_brand_aa2434_idx'),
        ),
    ]
