# Generated by Django 5.2.17 on 2026-08-11 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_store_produ_active_ee2f66_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('order', 'Order'), ('payment', 'Payment'), ('inventory', 'Inventory'), ('review', 'Review'), ('customer', 'Customer'), ('account', 'Account'), ('system', 'System')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_notifications_email',
            field=models.EmailField(blank=True, default='', help_text='Admin emails for new orders, payments, reviews and system alerts.', max_length=254),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['for_staff', 'read'], name='store_notif_for_sta_e62daa_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read'], name='store_notif_user_id_72f095_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='store_notif_user_id_c0d189_idx'),
        ),
    ]
