# Generated by Django 5.2.17 on 2026-08-13 19:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_notification_category_notification_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sales_channel',
            field=models.CharField(choices=[('online', 'Online store'), ('pos', 'Store point of sale')], default='online', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='served_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who served this order at the till.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Product cost price at the time of sale (for COGS/margin reporting).', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode/EAN for POS scanning. Leave blank to omit.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit cost of the product, used for margin/COGS reporting.', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Net units sold across all channels (kept in sync automatically).'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa STK Push'), ('cod', 'Cash / manual payment'), ('card', 'Card payment')], default='cod', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa STK Push'), ('manual', 'Cash / manual'), ('card', 'Card payment')], default='mpesa', max_length=10),
        ),
        migrations.CreateModel(
            name='PosSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash float at the start of the shift.', max_digits=12)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Cash physically counted at the end of the shift.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Cashier who opened this shift.', on_delete=django.db.models.deletion.CASCADE, related_name='pos_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pos_session',
            field=models.ForeignKey(blank=True, help_text='POS shift during which this in-store sale was made.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.possession'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['status'], name='store_posse_status_0a41f5_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['user', 'status'], name='store_posse_user_id_ae45cf_idx'),
        ),
    ]
