# Generated by Django 5.2.17 on 2026-08-24 07:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_sales_channel_order_served_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pos_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('other', 'Other')], default='', help_text='Exact till payment option chosen by the cashier.', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='pos_token',
            field=models.CharField(blank=True, help_text='Client-supplied idempotency token for POS sales so a retried request can never create a duplicate sale.', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cash actually handed over at the till (POS cash sales).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='change_given',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Change returned to the customer (POS cash sales).', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventorychange',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('sale', 'Sold'), ('restock', 'Restocked'), ('adjust', 'Adjusted'), ('release', 'Stock released'), ('return', 'Customer return'), ('threshold', 'Threshold changed'), ('desired', 'Desired level changed')], default='adjust', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('restocked', models.BooleanField(default=True, help_text='Whether the goods went back into sellable stock.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='store.orderitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='store.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order return',
                'verbose_name_plural': 'Order returns',
                'ordering': ['-created_at'],
            },
        ),
    ]
